version: '3.4'

services:
  cli:
    build:
      context: .
      target: cli_base
      args:
        CLI_VERSION: 1.1.19

  cli-dev:
    build:
      context: .
      target: cli_development
    volumes:
      - ./:/var/run/cli/
