version: '3.4'

services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile
      target: cli_base
      args:
        CLI_VERSION: 1.1.42
    env_file:
      - ./config.env
    volumes:
      - .:/var/run/cli/

  cli-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: cli_development
      args:
        CLI_VERSION: 1.1.42
    volumes:
      - .:/var/run/cli/
    env_file:
      - ./config.env
