FROM python:3.8-slim-buster
# or
#FROM nvcr.io/nvidia/pytorch:21.03-py3

# startup this directory server stuff
RUN mkdir /app
COPY ./setup.py /app
COPY ./project.py /app
COPY ./requirements/prod.txt /app/requirements.txt
COPY ./requirements/runner.txt /app/runner.txt
WORKDIR /app
RUN pip install -r requirements.txt
RUN pip install -e .
