name: Upload Python Package

on:
 release:
   types: [published]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry twine

    - name: Build package
      run: |
        poetry env use `which python3.8`
        poetry build

    - name: Publish package
      run: |
        poetry config pypi-token.pypi ${{ secrets.PYPI_API_TOKEN }}
        poetry publish

    - name: Yank package version
      env:
        PYPI_API_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
      run: |
        PACKAGE_NAME=$(poetry version | awk '{print $1}')
        PACKAGE_VERSION=$(poetry version | awk '{print $2}')
        echo "Marking $PACKAGE_NAME==$PACKAGE_VERSION as yanked"
        twine yank --username __token__ --password $PYPI_API_TOKEN --yes $PACKAGE_NAME==$PACKAGE_VERSION
